openapi: 3.0.0
info:
  version: 0.0.0
  title: 'Example: basic with immutability'
paths:
  /pets:
    get:
      operationId: listPets
      tags:
        - Pets
      summary: List pets
      parameters:
        - name: perPage
          description: Per page
          schema:
            type: string
            default: '20'
          in: query
          required: false
        - name: page
          description: Page number
          schema:
            type: string
            default: '1'
          in: query
          required: false
        - name: orderBy
          description: Order by
          schema:
            type: string
          in: query
          required: false
      responses:
        '200':
          description: List succeeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  pets:
                    type: array
                    items:
                      $ref: '#/components/schemas/PetResponse'
                  pages:
                    $ref: '#/components/schemas/PaginationResponse'
              examples:
                pet1:
                  value:
                    pagination:
                      firstPage: '1'
                      lastPage: '10'
                      nextPage: '2'
                      prevPage: '1'
                    pets:
                      - name: molestiae
                      - name: sit
                      - name: cum
                      - name: aperiam
                      - name: aliquid
                      - name: quibusdam
                      - name: sapiente
                      - name: ut
                      - name: aperiam
                      - name: enim
                      - name: ut
                      - name: et
                      - name: dolorem
                      - name: deserunt
                      - name: facere
                      - name: ut
                      - name: voluptas
                      - name: eveniet
                      - name: architecto
                      - name: eos
                pet2:
                  value:
                    pagination:
                      firstPage: '1'
                      lastPage: '10'
                      nextPage: '2'
                      prevPage: '1'
                    pets:
                      - name: placeat
                      - name: tempore
                      - name: dolorem
                      - name: excepturi
                      - name: aut
                      - name: error
                      - name: minus
                      - name: ipsa
                      - name: perspiciatis
                      - name: cupiditate
                      - name: illo
                      - name: asperiores
                      - name: in
                      - name: est
                      - name: voluptas
                      - name: quod
                      - name: facere
                      - name: molestiae
                      - name: quam
                      - name: quia
                pet3:
                  value:
                    pagination:
                      firstPage: '1'
                      lastPage: '10'
                      nextPage: '2'
                      prevPage: '1'
                    pets:
                      - name: sunt
                      - name: consectetur
                      - name: consequuntur
                      - name: sed
                      - name: reprehenderit
                      - name: tenetur
                      - name: facilis
                      - name: non
                      - name: earum
                      - name: commodi
                      - name: omnis
                      - name: fugiat
                      - name: et
                      - name: consequatur
                      - name: rerum
                      - name: aut
                      - name: et
                      - name: molestiae
                      - name: nobis
                      - name: a
                pet4:
                  value:
                    pagination:
                      firstPage: '1'
                      lastPage: '10'
                      nextPage: '2'
                      prevPage: '1'
                    pets:
                      - name: fuga
                      - name: dolore
                      - name: consequatur
                      - name: magnam
                      - name: autem
                      - name: rerum
                      - name: expedita
                      - name: ab
                      - name: aut
                      - name: possimus
                      - name: esse
                      - name: laboriosam
                      - name: ut
                      - name: totam
                      - name: dolore
                      - name: labore
                      - name: provident
                      - name: est
                      - name: dolorem
                      - name: excepturi
                pet5:
                  value:
                    pagination:
                      firstPage: '1'
                      lastPage: '10'
                      nextPage: '2'
                      prevPage: '1'
                    pets:
                      - name: cum
                      - name: quis
                      - name: qui
                      - name: sint
                      - name: quis
                      - name: aut
                      - name: ex
                      - name: voluptate
                      - name: alias
                      - name: amet
                      - name: nostrum
                      - name: mollitia
                      - name: aliquam
                      - name: placeat
                      - name: error
                      - name: id
                      - name: error
                      - name: eius
                      - name: magnam
                      - name: quia
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      operationId: createPet
      tags:
        - Pets
      summary: Create pet
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PetRequest'
            examples:
              pet1:
                value:
                  name: voluptas
              pet2:
                value:
                  name: aperiam
              pet3:
                value:
                  name: voluptatem
              pet4:
                value:
                  name: voluptatibus
              pet5:
                value:
                  name: ratione
      responses:
        '201':
          description: Create succeeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  pet:
                    $ref: '#/components/schemas/PetResponse'
              examples:
                pet1:
                  value:
                    pet:
                      name: quia
                pet2:
                  value:
                    pet:
                      name: fuga
                pet3:
                  value:
                    pet:
                      name: voluptatem
                pet4:
                  value:
                    pet:
                      name: voluptatibus
                pet5:
                  value:
                    pet:
                      name: ut
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/pets/{petId}':
    head:
      operationId: checkPet
      tags:
        - Pets
      summary: Check pet
      parameters:
        - in: path
          required: true
          name: petId
          schema:
            type: string
          description: Pet id
      responses:
        '200':
          description: Check succeeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmptyResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    get:
      operationId: getPet
      tags:
        - Pets
      summary: Get pet
      parameters:
        - in: path
          required: true
          name: petId
          schema:
            type: string
          description: Pet id
      responses:
        '200':
          description: Get succeeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  pet:
                    $ref: '#/components/schemas/PetResponse'
              examples:
                pet1:
                  value:
                    pet:
                      name: a
                pet2:
                  value:
                    pet:
                      name: voluptas
                pet3:
                  value:
                    pet:
                      name: reprehenderit
                pet4:
                  value:
                    pet:
                      name: quo
                pet5:
                  value:
                    pet:
                      name: ea
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      operationId: deletePet
      tags:
        - Pets
      summary: Delete pet
      parameters:
        - in: path
          required: true
          name: petId
          schema:
            type: string
          description: Pet id
      responses:
        '204':
          description: Delete succeeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmptyResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    EmptyResponse:
      type: object
    ErrorResponse:
      type: object
      properties:
        code:
          type: number
          readOnly: true
        message:
          type: string
          readOnly: true
        status:
          type: string
          readOnly: true
        details:
          type: array
          items:
            type: string
          readOnly: true
      required:
        - statusCode
        - message
    PaginationResponse:
      type: object
      properties:
        firstPage:
          type: number
        lastPage:
          type: number
        nextPage:
          type: number
        prevPage:
          type: number
      required:
        - firstPage
        - lastPage
        - nextPage
        - prevPage
    PetResponse:
      properties:
        name:
          type: string
    PetRequest:
      properties:
        name:
          type: string
